# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tableform',
                'doc_host': 'https://simonkeys.github.io',
                'git_url': 'https://github.com/simonkeys/tableform',
                'lib_path': 'tableform'},
  'syms': {'tableform.core': {'tableform.core.foo': ('core.html#foo', 'tableform/core.py')}}}
